# Generated by Django 4.2.5 on 2023-10-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_portfolio_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
